govdelivery.tms_settings:
  type: config_object
  label: 'Configuration'
  mapping: 
    accounts:
      type: sequence
      sequence:
        type: mapping
        mapping:
          fromname:
            type: string
          username:
            type: string
          password:
            type: string
    server:
      label: 'Server'
      description: 'Enter the URL of your GovDelivery TMS instance. It must begin with "https." Example: https://yourserver.govdelivery.com'
      type: string
    auth_token:
      label: 'Auth token'
      description: 'Enter the authentication token needed to send emails through your GovDelivery TMS service. If you do not have an authentication token, please content your GovDelivery account representative.'
      type: string
    enabled:
      label: 'Use TMS for Outbound Mail'
      description: "If this option is enabled, emails from your Drupal site will be sent using GovDelivery's Transactional Message Service (TMS). If it is disabled, emails we be sent using Drupal's standard SMTP-based email system."
      type: boolean
    queue:
      label: 'Queue Mail for high volume'
      description: 'If this option is enabled, messages will be placed in a queue for delivery rather than be sent immediately. (Messages that fail to send will be queued anyway for later delivery.)'
      type: boolean
    override_from:
      type: boolean
      label: 'Override the From address on outgoing messages and failback on the predefined From address in this module'
      description: 'This will allow webforms and other modules to configure the From address.'
    max_bid:
      type: integer
      label: 'Maximum bins used with queue asynchronous processing'