govdelivery_taxonomy.settings:
  type: config_object
  label: 'Configuration'
  mapping:
    username:
      label: 'WebService Administrator Username'
      type: string
    password:
      label: 'WebService Administrator Password'
      type: string
    clientcode:
      label: 'GovDelivery DCM Client Account Code'
      type: string
    api_server:
      label: 'GovDelivery API URL (Without HTTPS://)'
      type: string
    public_server:
      label: 'GovDelivery public URL (Without HTTPS://)'
      type: string
    drupalserver:
      label: 'Drupal Instance Base URL (Without HTTPS://)'
      description: 'This is the URL to this Drupal instance without any subdirectories'
      type: string
    categories:
      label: 'GovDelivery Category to Taxonomy Vocabulary mappings'
      type: sequence
      sequence:
        type: mapping
        mapping:
          vid:
            label: 'Drupal Vocabulary ID'
            type: string
          category_id:
            label: 'GovDelivery Category ID'
            type: string
    topics:
      label: 'GovDelivery Topics to Taxonomy Term mappings'
      type: sequence
      sequence:
        type: mapping
        mapping:
          tid:
            label: 'Drupal Term ID'
            type: string
          topic_id:
            label: 'GovDelivery Topic ID'
            type: string
    