<?php
/**
 * @file
 * GovDelivery Signup Module.
 *
 * Defines a Drupal block that can be used to let site visitors sign up
 * for GovDelivery email notifications.
 */

/**
 * Implements hook_theme().
 */
function govdelivery_signup_theme() {
  $path = drupal_get_path('module', 'govdelivery_signup') . '/theme';
  return array(
    'govdelivery_signup_displayform' => array(
      'render element' => 'form',
      'template' => 'govdelivery_signup-displayform',
      'path' => $path,
    ),
  );
}
